### ISSUE TITLE
Devise Token Authentication is Deprecated

### ISSUE THREAD

**Issue by DVG** [heartsentwined/ember-auth-rails-demo#10]
The devise team has removed Token Authentication from it's list of modules, citing that the module can be vunerable to timing attacks. They have some suggested alternatives in this gist: https://gist.github.com/josevalim/fb706b1e933ef01e4fb6

Wanted to make you aware so the demo could be updated.

**Comment by heartsentwined** [comment]
It is indeed deprecated. There are also notes specifically in the wiki that addresses this.

**Comment by DVG** [comment]
Ah, my bad, I missed the note in the header.
