### ISSUE TITLE
Best place to use RememberMe.recall()

### ISSUE THREAD

**Issue by AshesOfOwls** [heartsentwined/ember-auth-rails-demo#2]
Don't have a bug, just a question for you. I was wondering why you decided to put the Auth.Module.RememberMe.recall() within the didInsertElement function of the application view and not within the init function of the application route. I tried it and it seems to be working fine all the while triggering it slightly sooner. Is there a caveat to doing this that I am missing?

**Comment by heartsentwined** [comment]
My apologies for the delay.

I have released a new version of `ember-auth`. This new version will call `Auth.Module.RememberMe.recall()` automatically by default, eliminating the need for userland code on this method. You can read more about this feature in the [readme](https://github.com/heartsentwined/ember-auth#remember-me), and in this [issue](https://github.com/heartsentwined/ember-auth/issues/8#issuecomment-15664514).

**Comment by AshesOfOwls** [comment]
Excellent! Thanks!
