### ISSUE TITLE
When do you expect this will be brought up to 5.0?

### ISSUE THREAD

**Issue by ryw** [heartsentwined/ember-auth-rails-demo#4]
@heartsentwined thanks so much for knocking out the "big refactor" of ember-auth. As an Ember noob, I'm struggling to adapt code I got from https://github.com/joscas/base_app  — in particular how to fix first line of this: https://github.com/joscas/base_app/blob/master/app/assets/javascripts/controllers/sign_in_controller.js

Will the code of this demo app change a lot, based on v5.0 of ember-auth?

**Comment by heartsentwined** [comment]
In that case, v5.0 removed the boilerplate in v4.0 and lower, i.e.
- `Auth.SignInController` is gone - there is no need to include this mixin; instead, you load the `actionRedirectable` module
- there is no need to call `registerRedirect()` either
- `Auth.signIn({foo: 'bar'})` is now `App.Auth.signIn({data: {foo: 'bar'}})`, where `App` is your app namespace

However, if you are starting out, I suggest that you do not try to adapt from another app. joscas' app is actually quite good, but it includes _more_ than basic Getting Started material. In particular, it has implemented semi-advanced manual use of `transaction`s, but for starters the [model lifecycle callbacks](http://emberjs.com/guides/models/model-lifecycle/) would be sufficient.

The [docs](http://ember-auth.herokuapp.com) themselves would actually _generate_ the code that you need for `ember-auth`. I am also updating this demo to v5.0 - I'll let you know when I'm done.

**Comment by heartsentwined** [comment]
By the way, joscas himself is also doing the upgrade to v5.0, you might want to get in touch with him directly for advice if you are basing off his app.

**Comment by heartsentwined** [comment]
As for the code of this demo app, only the `auth` parts will change. If memory serves me correctly, the tutorial should still be valid all the way up to [Ember setup](https://github.com/heartsentwined/ember-auth-rails-demo/wiki/Ember-setup), the next chapter would be [Auth UI](https://github.com/heartsentwined/ember-auth-rails-demo/wiki/Auth-UI), where changes would be needed.

**Comment by heartsentwined** [comment]
Demo / tutorial updated to `5.x` / `6.x`.

**Comment by ryw** [comment]
Thanks for updating this @heartsentwined — the use case that I'm still struggling with is when I have a "secret route" that extends App.Auth.AuthRedirectable.

I'd like to be able to load the model when refreshed, but the complication is that the user might not be signedIn so no token, and 401 Unauthorized error happens loading the model data.

So I see code in base_app to transitionTo the current route, but transitionTo requires a model object passed to it, but I didn't get the model object due to the 401 Unauth problem :)

I'd love to see you drop a resource into this demo app that requires user be signedIn and calls the backend api correctly on browser load.

**Comment by heartsentwined** [comment]
Thanks for the feedback @ryw, this is indeed a thorny spot at the current implementation. I'm trying to figure out how to best implement this in `ember-auth` without incurring too much blocking overhead due to synchronous loading. I'll update both `ember-auth` and this demo when I got a good solution.

**Comment by heartsentwined** [comment]
Reopened as enhancement.

**Comment by heartsentwined** [comment]
Update: ember has got a new router, which is heavily relevant to authenticated-backed apps. I'm working with it to update ember-auth with the new APIs. For now, this enhancement is put on hold - the solution based on the new router is likely to be very different from one based on the previous router. I'll post an updated demo use case reflecting this after I finish with updating ember-auth.

Ref:
- [gist](https://gist.github.com/machty/5723945)
- [presentation](https://machty.s3.amazonaws.com/ember-facelift-presentation/index.html)

**Comment by heartsentwined** [comment]
@ryw your use case is now addressed with ember `rc6` and ember-auth `7.x` releases. The logic behind it is different though, in that
- previously, you expect it to not load an auth-only model, but display the same template anyway (probably with message targeted at non-authenticated users)
- now, you should redirect non-authenticated users away to another (non-auth only) route (and probably display a "please sign in" message)

In other words,

> the new router now _encourages_ you to use `authRedirectable` as "the ember way" of solving auth-only routes (with auth-only models)

---

`7.x` branch now released, with rc6 (new router!) support. [changelog](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md), [upgrade guide](https://github.com/heartsentwined/ember-auth/blob/master/CHANGELOG.md#upgrade-guide), [docs](http://ember-auth.herokuapp.com/docs) and [demo](https://github.com/heartsentwined/ember-auth-rails-demo/) all properly updated. Main notes:
- `ember-auth` now _requires_ ember `rc6` or above
- the new router now _encourages_ you to use `authRedirectable` as "the ember way" of solving auth-only routes (with auth-only models)
- thus you might want to pair it with `actionRedirectable` too for user experience
- despite this being a major version update, it would likely not break most userland code; the BC breaks are not in main, documented API
