### ISSUE TITLE
addHandler

### ISSUE THREAD

**Issue by bseng** [heartsentwined/ember-auth-rails-demo#8]
Before `9.0` it is quite obvious in the docs where we can use addHandler (i.e. right after Ember.Auth.Create). But after `9.0` it is not so, as Ember.Auth.Extend does not have `@auth`. Can you update the rails demo to show the best practice for addHandler for things like signInSuccess? 

Thanks.

**Comment by heartsentwined** [comment]
Several pointers:
1. Not recommended to do it in the global namespace.
2. You are recommended to access the `auth` where it is injected to. By default that's routes, controllers, and views.
3. Or you might want a separate service object, for that. You can build one [like this](https://github.com/heartsentwined/ember-auth/issues/119#issuecomment-26709616), inject the `auth` into your object, and perhaps register the handler on `init` or whatever fits your business logic.

**Comment by bseng** [comment]
Thanks for the link. 

For the signInSuccess addHandler scenario, if I were to inject it on either routes, controllers and views, will it get pick up by other login in means like rememberable or auth-token?

I quite like the separate service object I guess there's should be more guidance like that in the rails demo code or the docs page.

**Comment by heartsentwined** [comment]
Then I'd recommend you go with the service object.

I didn't put that in because it would bloat the demo up. Besides, that's just the standard ember way of using dependency injections, nothing `ember-auth` specific.

**Comment by bseng** [comment]
will do~ thanks.
